### ISSUE TITLE
Flame graph

### ISSUE THREAD

**Issue by vlascik** [rwjblue/heimdalljs-visualizer#7]
The visualization could be more intuitive with a flame graph, seems like a better way to see the relative time builds take, with ability to drill down. There's a nice library for this at 

https://github.com/brendangregg/FlameGraph
http://www.brendangregg.com/flamegraphs.html
Some D3 versions:
https://github.com/cimi/d3-flame-graphs
https://github.com/spiermar/d3-flame-graph

Seems to be the same one used in Chrome DevTools in Performance tab.

**Comment by rwjblue** [comment]
Yep, this is absolutely on my "todo list".  Would love help on it if you (or anyone else) has the time...

**Comment by vlascik** [comment]
I honestly wouldn't know where to start, but maybe @stefanpenner @trentmwillis & co. would be able to do it rather quickly? Seems that they already did something similar in 
https://github.com/ember-best-practices/ember-perf-timeline

**Comment by rwjblue** [comment]
@vlascik - that utilizes the built in flame graph tooling in the chrome dev tools, it doesn't (AFAIK) generate its own interactive flamegraphs.

**Comment by hjdivad** [comment]
@rwjblue yeah ember-perf-timeline is just doing `console.time` and relying on chrome to include it above the flamegraph.

**Comment by vlascik** [comment]
So, update, I already implemented this, the only problem is that every d3 flamegraph library I found was done for D3 3.x (global, no modules, this app uses 4.x), so I will have to create a fork there (and do a couple more fixes in related ember addons). 
I will post a WIP PR in next few days.

**Comment by rwjblue** [comment]
@vlascik - AWESOME! thank you!!!

**Comment by rwjblue** [comment]
Fixed by #8
